import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Passions_Conflict,
  Fraunces,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const passionConflict = Passions_Conflict({
  variable: "--font-passionconflict",
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          passionConflict.variable,
          inter.variable,
          fraunces.variable,
          montserrat.variable,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
